# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Merge
version:      3.53
version_from: lib/HTML/Merge/Compile.pm
installdirs:  site
requires:
    DBD::SQLite:                   0
    DBI:                           0
    Term::ReadLine:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
